### ISSUE TITLE
Editor: Strahler drehen

### ISSUE THREAD

**Issue by bitfasching** [maddin1982/derTurm#10]
Wir haben die Strahler im Turm extra so eingerichtet, dass die im Editor mittigen Strahler auch mittig über dem Haupteingang der Technischen Sammlungen stehen. Es wäre gut, wenn sowohl im 3D-Modell als auch im 2D-Kreis die mittigen Fenster 7 und 8 zur Kreuzung bzw. nach unten zeigen.

**Comment by bitfasching** [comment]
Huch, kann ich gar nicht mehrere Leute dem Issue zuordnen? :D

**Comment by frauzufall** [comment]
Für die 2D-Version ist es gelöst.

**Comment by SqiSch** [comment]
passt das nicht schon für das HQ model?

**Comment by frauzufall** [comment]
nee. der haupteingang ist vorn, wenn auf der rechten seite des hauses der durchgang rauskommt.

**Comment by SqiSch** [comment]
Ne, das model ist alt und das Gebäude wurde umgebaut. 
Der Haupteingang ist auf der Hauptstraße, der kleine Eingang (bei der Brücke)  existiert nicht mehr. Stattdessen sind da jetzt Fenster und ein Fahrradständer. (google maps hat auch nur alte fotos)

**Comment by frauzufall** [comment]
Genau so meine ich es doch. Die mittleren Strahler sind aber nicht dort drüber.

**Comment by SqiSch** [comment]
ach. Okay.. nicht das erste Fenster im Editor soll dort positioniert sein sonder die  position 6,7 im editor dort wo jetzt pos 1 angezeigt wird. Ist schon spät ;)

**Comment by SqiSch** [comment]
ich glaube am einfachsten ist es die fenster im 3d model zu drehen. Hab aber keine ahnung wie der export dann läuft.. Bitte jemand anderes machen ;)

**Comment by SqiSch** [comment]
Done für HQ model. code nicht schön aber funktioniert.

**Comment by bitfasching** [comment]
Danke euch. :)
Aber damit die Animation wirklich zur Kreuzung zeigt, müsste in beiden Fällen die Reihe noch um ein Fenster gegen den Uhrzeigersinn gedreht werden. (Wir haben 16 Fenster, es müssen also Fenster 7 und 8 zur Kreuzung zeigen, nicht 6 und 7.)

**Comment by bitfasching** [comment]
Ah, und die Reihenfolge der Fenster ist im HQ-Modell und im Kreis verkehrt! Ich habe einen Spinner, der von links nach rechts läuft. Er müsste an der mir zugewandten Seite des Turms auch von links nach rechts, also gegen den Uhrzeigersinn laufen.

**Comment by frauzufall** [comment]
Die Reihenfolge für 2D hab ich geändert. Die Mittigkeit stimmt aber, denke ich? Bei 3D sehe ich auch, dass es noch versetzt ist, aber im Kreis sind es die beiden unteren Fenster...?
![screenshot - 22 01 2015 - 10 25 27](https://cloud.githubusercontent.com/assets/708121/5853332/eeebf656-a222-11e4-9e68-daa79b811a66.png)

**Comment by frauzufall** [comment]
ah, jetzt seh ichs. du meinst fenster 7 und 8, wenn du am anfang nicht fenster 1, sondern fenster 0 zählst... ;) änder ich gleich!

**Comment by bitfasching** [comment]
Genau! Danke! :)
