### ISSUE TITLE
umschaltfunktion zwischen einfachem turm und komplexem model des ernemannturms

### ISSUE THREAD

**Issue by maddin1982** [maddin1982/derTurm#7]
im einstellungsdialog für das 3d fenster soll das angezeigte model ausgewählt werden können
- zusätzlich wäre auch eine darstellung ganz ohne webgl (16 divs , die die Farben anzeigen) für manche anzeigegeräte hilfreich (zb iphone, ipad)
- diese option müsste ebenfalls im einstellungsdialog angeboten werden und bei aufruf der anwendung von einem mobilen gerät wie dem iphone als default gelten

**Comment by SqiSch** [comment]
Done.. Plase review it.
